# Generated by Django 5.1.7 on 2025-03-28 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('set_code', models.CharField(max_length=10)),
                ('collector_number', models.CharField(max_length=10)),
                ('mana_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('cmc', models.FloatField(default=0)),
                ('type_line', models.CharField(blank=True, max_length=255, null=True)),
                ('oracle_text', models.TextField(blank=True, null=True)),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
                ('toughness', models.CharField(blank=True, max_length=10, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=10, null=True)),
                ('rarity', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('set_code', 'collector_number')},
            },
        ),
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Use -1 to represent infinite quantity (e.g., for basic lands)')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.card')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
            ],
            options={
                'unique_together': {('collection', 'card')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(through='collection.CollectionCard', to='collection.card'),
        ),
        migrations.CreateModel(
            name='Decklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decklists', to='collection.collection')),
            ],
        ),
        migrations.CreateModel(
            name='DecklistCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Minimum quantity is 1', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_sideboard', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.card')),
                ('decklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.decklist')),
            ],
            options={
                'unique_together': {('decklist', 'card', 'is_sideboard')},
            },
        ),
        migrations.AddField(
            model_name='decklist',
            name='cards',
            field=models.ManyToManyField(through='collection.DecklistCard', to='collection.card'),
        ),
    ]
