# Generated by Django 5.1.7 on 2025-03-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scryfall_uri',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
