# Generated by Django 5.1.7 on 2025-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_card_scryfall_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklist',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates if this deck is intended to be physically constructed'),
        ),
    ]
